name: Twitter Bot Scheduler

on:
  schedule:
    - cron: '0,30 16-21 * * *'  # Setiap 30 menit dari 16:00-21:59 UTC (23:00-04:59 WIB)
  workflow_dispatch:  # Untuk trigger manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install tweepy
    
    - name: Run Twitter Bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python twitter_bot.py
