name: Twitter Auto-Post Bot

on:
  schedule:
    # Waktu UTC (WIB = UTC+7)
    - cron: '*/5 16-20 * * *'  # Jalankan setiap 5 menit dari 16:00-20:59 UTC
  workflow_dispatch:  # Untuk trigger manual

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install tweepy --upgrade
      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
