name: Twitter Bot Scheduler

on:
  schedule:
    - cron: '0,15,30,45 3 * * *'    # Setiap 15 menit dari 03:00-03:45 UTC
    - cron: '0,15,30,45 15 * * *'   # Setiap 15 menit dari 15:00-15:45 UTC
    - cron: '0,30 16-20 * * *'      # Setiap 30 menit dari 16:00-20:00 UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install tweepy
      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
