name: 24/7 Twitter Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Setiap 15 menit, 24/7
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install tweepy
        
      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python twitter_bot.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add schedule_history.json
          git commit -m "Update posting history" || echo "No changes"
          git push
