name: Twitter Auto-Post Bot

on:
  schedule:
    - cron: '0-15 17 * * *'    # 00:00-00:15 WIB
    - cron: '25-40 17 * * *'    # 00:25-00:40 WIB
    - cron: '0-15 18 * * *'     # 01:00-01:15 WIB
    - cron: '25-40 19 * * *'    # 02:25-02:40 WIB
    - cron: '25-40 16 * * *'    # 23:25-23:40 WIB
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install tweepy
      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
