name: Twitter Bot Scheduler

on:
  schedule:
    - cron: '0,30 3 * * *'    # 03:00 & 03:30 UTC (antisipasi delay)
    - cron: '0,30 15 * * *'   # 15:00 & 15:30 UTC (antisipasi delay)
    - cron: '0,30 16-20 * * *' # Setiap 30 menit dari 16:00-20:00 UTC
  workflow_dispatch:           # Untuk trigger manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install tweepy
      - name: Run Bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python twitter_bot.py
